# -*- coding: utf-8 -*-
"""Activity4_2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gwuXI803zJ8BuHq6_1KDQKoOOCtDSthw
"""

import streamlit as st
import pandas as pd
import numpy as np

st.title('Kent County Housing')
df = pd.read_csv('https://storage.googleapis.com/scsu-data-science/kc_house_mini.csv')

st.markdown('---')
st.subheader('Price Range')
price = st.slider("What's your price range?", 80000, 3080000, value=(100000, 200000), step=100)
st.write("Your price range is", price)

st.markdown('---')
st.subheader('Number of Bedrooms')
num_bedrooms = st.selectbox(
    'How many bedrooms?',
    ('0', '1', '2', '3', '4', '5', '6', '7'))
st.write('You selected:', num_bedrooms)

filtered_df = df[
    (df['price'] >= min_price_slider) &
    (df['price'] <= max_price_slider) &
    (df['bedrooms'] == num_bedrooms)]

st.write(f'Filtered dataset (showing {len(filtered_df)} houses):')
st.dataframe(filtered_df)

if not filtered_df.empty:
    st.map(filtered_df[['lat', 'lon']])
else:
    st.write('No houses match the selected criteria.')